server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location /api/golang/ {
        proxy_pass http://golang:8080/api/golang/;
    }

    location /api/spring/ {
        proxy_pass http://spring:8080/api/spring/;
    }

    location /api/dotnet/ {
        proxy_pass http://dotnet:8080/api/dotnet/;
    }

    location /api/django/ {
        proxy_pass http://django:8080/api/django/;
    }

    location /ping {
        proxy_pass http://golang:8080/ping;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
